### ISSUE TITLE
Make Relative works only one way, for % Target with fixed step (min = max)

### ISSUE THREAD

**Issue by vonglan** [helgoboss/realearn#641] opened 2022-08-18 19:55 UTC
I am sure this worked before.
Target is a waveform with only 5 different values, target max = 100%, so I set step min = step max = 20.5%.
When I turn the physical button left, the VST parameter gets the correct values. But when I turn it right, the VST parameter is not changed.
Version 2.13.1
For a "continuous" parameter (cutoff, target max = 10000), both ways work correctly.

Log output:
1660851985.870 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.3898100845953998 during normal control
1660851985.874 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0117647058823529 at Instant { t: 45533475401 } (matched)
1660851985.876 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851985.880 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45534627416 } (matched)
1660851985.990 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851985.994 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45536355467 } (matched)
1660851985.996 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851986.000 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45537507472 } (matched)
1660851986.110 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851986.114 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45539235518 } (matched)
1660851986.230 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929056 during normal control
1660851986.234 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274510775 at Instant { t: 45542435597 } (matched)
1660851986.348 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851986.353 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45545123892 } (matched)
1660851986.410 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851986.415 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45547043931 } (matched)
1660851986.529 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851986.534 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45550179992 } (matched)
1660851986.707 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851986.714 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45553508084 } (matched)
1660851986.769 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851986.775 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45555812136 } (matched)
1660851986.888 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929062 during normal control
1660851986.894 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.003921568627451022 at Instant { t: 45558564225 } (matched)
1660851986.947 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851986.954 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45560100341 } (matched)
1660851987.129 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851987.135 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45564132442 } (matched)
1660851987.548 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20080284750929067 during normal control
1660851987.555 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value -0.0039215686274509665 at Instant { t: 45573668633 } (matched)
1660851990.369 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.21256755339164357 during normal control
1660851990.375 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.007843137254901933 at Instant { t: 45641638603 } (matched)
1660851990.379 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.2086459847641926 during normal control
1660851990.385 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.0039215686274509665 at Instant { t: 45642662164 } (matched)
1660851990.459 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20864598476419266 during normal control
1660851990.465 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.003921568627451022 at Instant { t: 45644070206 } (matched)
1660851990.520 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.2086459847641926 during normal control
1660851990.527 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.0039215686274509665 at Instant { t: 45645670241 } (matched)
1660851990.577 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.2086459847641926 during normal control
1660851990.581 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.0039215686274509665 at Instant { t: 45647526266 } (matched)
1660851990.699 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.2086459847641926 during normal control
1660851990.707 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.0039215686274509665 at Instant { t: 45649958345 } (matched)
1660851990.937 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.2086459847641926 during normal control
1660851990.945 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.0039215686274509665 at Instant { t: 45655910487 } (matched)
1660851991.239 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.2086459847641926 during normal control
1660851991.247 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.0039215686274509665 at Instant { t: 45663526750 } (matched)
1660851991.479 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.20864598476419272 during normal control
1660851991.487 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.0039215686274510775 at Instant { t: 45668006834 } (matched)
1660851991.779 | ReaLearn xFSIHxbQ | Target control   | Mapping 2: Hit target with value 0.2086459847641926 during normal control
1660851991.787 | ReaLearn xFSIHxbQ | Virtual control  | Multi SY/Osc1Waveform with value +0.0039215686274509665 at Instant { t: 45676199296 } (matched)

Mapping:
{
    kind = "Mapping",
    value = {
        id = "73f20c71-43a2-4f9b-90bf-72881285cf46",
        name = "2",
        source = {
            kind = "Virtual",
            id = "SY/Osc1Waveform",
        },
        glue = {
            step_size_interval = {0.205, 0.205},
            step_factor_interval = {1, 5},
        },
        target = {
            kind = "FxParameterValue",
            parameter = {
                address = "ById",
                fx = {
                    address = "ByName",
                    chain = {
                        address = "Track",
                    },
                    name = "*Reaktor*",
                },
                index = 10,
            },
        },
    },

**Comment by helgoboss** [comment] 2022-08-19 18:48
Mmh, I think this is not only related to "Make relative" but to relative control with step counts (discrete) in general. My guess is that it's FX specific. Can you reproduce it with a stock plugin?

**Comment by helgoboss** [comment] 2022-08-19 18:52
Ah, wait. It could actually have something to do with a recent change. Remember our discussion how step_size_interval and step_factor_interval had to represent the same values in Lua (or alternatively only one of them can be present)? I lifted this restriction. These are now completely independent settings. I see in your Lua code that those intervals are different.

**Comment by vonglan** [comment] 2022-08-21 20:25
Hi Benjamin,

I can't remember the discussion about step_size_interval and step_factor_interval.

Anyway, I removed the step_size_factor via Lua code Ex/Import (it is not visible in the GUI anyway).
Result: The problem is still the same (VST reacting only in one direction), but in addition, moving the physical button half of the range, now moves the VST value all the way from highest to lowest.

I also checked with the u-he Repro plugin (the original problem was with NI Monark). Here, the VST value does not move either way. Step size is a bit different in this case:

        glue = {
            step_size_interval = {0.3333, 0.3333},
            step_factor_interval = {1, 5},
        },

I also tried relative encoders (Behringer X-Touch Mini) with NI Monark: Now, the discrete targets (octave) worked fine, whereas the "continuous" (fine tuning) did not work in a visible way.
They only show really tiny value changes in the log, which do not show up in the VST GUI:
1661112990.754 | ReaLearn 6tiX3fjw | Virtual control  | Multi SY/Osc3PitchFine with value +1 at Instant { t: 253862320233 } (matched)
1661113010.183 | ReaLearn 6tiX3fjw | Target control   | Mapping 12: Hit target with value 0.5064259337450494 during normal control
1661113010.191 | ReaLearn 6tiX3fjw | Virtual control  | Multi SY/Osc3PitchFine with value -1 at Instant { t: 254328699815 } (matched)
1661113010.485 | ReaLearn 6tiX3fjw | Target control   | Mapping 12: Hit target with value 0.5063259171511163 during normal control
1661113010.493 | ReaLearn 6tiX3fjw | Virtual control  | Multi SY/Osc3PitchFine with value -1 at Instant { t: 254335676076 } (matched)
1661113010.663 | ReaLearn 6tiX3fjw | Target control   | Mapping 12: Hit target with value 0.5062259005571832 during normal control
1661113010.671 | ReaLearn 6tiX3fjw | Virtual control  | Multi SY/Osc3PitchFine with value -1 at Instant { t: 254340540296 } (matched)
1661113010.844 | ReaLearn 6tiX3fjw | Target control   | Mapping 12: Hit target with value 0.5061258839632501 during normal control
1661113010.851 | ReaLearn 6tiX3fjw | Virtual control  | Multi SY/Osc3PitchFine with value -1 at Instant { t: 254344572397 } (matched)
1661113011.024 | ReaLearn 6tiX3fjw | Target control   | Mapping 12: Hit target with value 0.506025867369317 during normal control
1661113011.033 | ReaLearn 6tiX3fjw | Virtual control  | Multi SY/Osc3PitchFine with value -1 at Instant { t: 254349244453 } (matched)
1661113011.205 | ReaLearn 6tiX3fjw | Target control   | Mapping 12: Hit target with value 0.5059258507753839 during normal control
1661113011.215 | ReaLearn 6tiX3fjw | Virtual control  | Multi SY/Osc3PitchFine with value -1 at Instant { t: 254353724110 } (matched)
1661113011.414 | ReaLearn 6tiX3fjw | Target control   | Mapping 12: Hit target with value 0.5058258341814508 during normal control

In the ReaLearn Mapping GUI, I see that the VST value is changed, but only from 5000 (middle position) to 5001, then 5002 etc.

Mapping in this case is:        glue = {
            step_size_interval = {0.1, 1},
            step_factor_interval = {1, 5},
        },


Additional note (not important, but might be related):

I also noted , that "make relative" does not work for what I call " 1 to 2" mappings, where one knob controls two VST switches  (e.g. Waveform knob mapping to Sawtooth switch plus Pulse switch), mapping to (0,0), (0,1) (1,0) (1,1) using an EEL fornula

y=(2*x/1.00001)-floor(2*x/1.00001)

for the second VST parameters. Using "make relative", both VST switches jump at the same time now. However, I not 100% sure whether this worked before, and anyway it is not an important function.

**Comment by helgoboss** [comment] 2022-08-21 20:30
Ah, seems like you are running into the NI plug-in issue. They have parameters that report themselves as having 10000 steps, which is ridiculous. So you need to enter a speed min larger than 100 (only possible via text field input) to have any meaningful changes.

I think there's an issue already in which I wanted to add a "Force continuous" checkbox to deal exactly with this kind of problem.

**Comment by vonglan** [comment] 2022-08-21 20:59
Yes, setting step size to 100 for the NI-related main mapping helps for the "continuous" targets with 10000 steps.
I thought this worked before, but I am not sure.

The original problem (discrete VST parameter effected by "make relative" in only one way, or not at all in case of u-he plugin) is unsolved.
I tried with ReaSamplOmatic5000 (is that what you meant with "stock plugin"?), with parameter "MIDI channel". No problem with that. But it looks in the ReaLearn mapping display as if that is not really a discrete parameter. Do you know any Reaper stock plugin with a discrete parameter?

**Comment by helgoboss** [comment] 2022-08-21 21:09
Mmh, good question 😆 I think the JS effect parameters are often discrete, would have to check.

But I also have access to all Komplete 9 instruments, so I could also check if you send me a small project file.

**Comment by vonglan** [comment] 2022-08-22 16:09
Here is an example file with Monark.
[issue 641.RPP.zip](https://github.com/helgoboss/realearn/files/9395876/issue.641.RPP.zip)
When you play it, first the mode (parameter 2) is set to "relative", then the physical knob was moved right (not transferred to  VST parameter - Waveform Oscillator 1), then left (transferred correctly).

By the way: At first I was irritated that the NRPNs would not record into the MIDI item. Reason was that I had accidentally  set ReaLearn's control input to the Device, instead of <input FX>. It seems this is not mentioned in the user guide.

**Comment by helgoboss** [comment] 2022-08-23 08:21
Will look into it. The reason why messages are not recorded on the track of you choose the device as control unit is that you have "Let through: Matched" probably disabled. That takes the message out of the global stream. It will never arrive at the tracks. One of my favorite ReaLearn features. (Is mentioned in the corresponding part of the user guide.)

**Comment by vonglan** [comment] 2022-08-23 19:50
ok, thanks. Ah, of course, the control input selector and the "Let through" checkbox work in tandem.

I also noticed (positively): when I set control input to the Device, I can record the VST parameter movements (that result from the NRPNs/CCs and ReaLearn) in Reaper automation lanes.

**Comment by helgoboss** [comment] 2022-11-15 16:47
The problem with this Monark "Waveform Oscillator" parameter is that it insists on having very discrete values but
doesn't report a step size.

- With absolute control, this is no problem because you can swipe over the whole range and
Monark will automatically round to the closest discrete value.
- With normal relative control, this only works if you figure out the correct step size and tell it ReaLearn. E.g. by
  using the target value fader and check the percentage of the second value (20.4724% in this case). With
  the default min step size of 1%, it doesn't move forward at all because 0% + 1% is much closer to 0% than to 20.4724%.
  So it tries to hit the target with 1% but the target rounds it back to 0% ... so we are back where we started :)
- With "Make relative", this doesn't work at all because at the moment there's no option to force a specific step size.

**Comment by helgoboss** [comment] 2022-11-15 16:50
So technically, it's a missing feature/bug in Monark/Reaktor. We all know that NI won't fix this (I wouldn't as well because it would break backward compatibility). So you need to wait for #702 to be able to work around it.

**Closed by helgoboss** 2022-11-15 16:50 UTC
Labels: bug, question, next

**Comment by vonglan** [comment] 2022-11-19 07:00
> * With normal relative control, this only works if you figure out the correct step size and tell it ReaLearn. E.g. by
>   using the target value fader and check the percentage of the second value (20.4724% in this case).

This is what I do (see first post here), in all my presets.

The problem is that it stopped working one direction. They other direction it works as before. I did not change Monark or the mapping. Reminds me of my other issue #736, and your fix in #615. Could this have anything to do with it?

**Comment by helgoboss** [comment] 2022-11-19 08:21
The title has "Make relative" and in other posts you also mention that you use that. Isn't it related to that? It can't work with "Make relative" at the moment.

When I use normal relative control (not "Make relative"), it works here when I find the right step size, in both directions. Maybe you are using an encoder and configured it with the wrong relative type.

**Comment by vonglan** [comment] 2022-11-20 20:46
Sorry, forget my post "This is what I do ...", I was confused.
The problem is with "make relative", not with true relative (encoders).

But it is not important. I can always switch to absolute mode (the SY presets have "make relative" and "absolute").
