### ISSUE TITLE
Certain preset causing slowdowns

### ISSUE THREAD

**Issue by arthurmcarthur1** [helgoboss/realearn#553] opened 2022-04-08 04:59 UTC
I've been experiencing some performance issues (sluggish UI and unresponsiveness) and have narrowed it down to a particular preset in ReaLearn created with a previous version (I'm on latest pre). 

When this JSON is loaded in any ReaLearn instance in my project (armed or unarmed, monitor or regular), performance starts to suffer dramatically once there are over ~150 tracks. It's not a particularly huge ReaLearn preset (171 mappings) so I'm wondering if this is a bug.

**Comment by arthurmcarthur1** [comment] 2022-04-08 05:00
[json.txt](https://github.com/helgoboss/realearn/files/8448669/json.txt)

**Comment by helgoboss** [comment] 2022-04-08 09:01
Thanks. Unfortunately I can't really check anything with that preset because it involves 3rd-party plug-ins. Any chance you can replicate it with stock plug-ins?

Also very relevant in this regard: Is ReaLearn UI open or closed? When the ReaLearn UI is open, it's usually several orders of magnitude slower. So be sure to close the UI before making any speed tests.

**Comment by arthurmcarthur1** [comment] 2022-04-08 15:24
[json(1).txt](https://github.com/helgoboss/realearn/files/8452072/json.1.txt)

The slowdown is happening with the UI closed as well. Here's a version with all references to FX removed. It runs better than the other one, but still slows down significantly when the project gets around 500 tracks. I am adding, duplicating tracks, scrolling and selecting. REAPER gets less and less responsive the more tracks are added.

https://s7.gifyu.com/images/37a34f5adba221a1f3.gif

**Comment by helgoboss** [comment] 2022-04-08 16:01
Sorry, forgot to mention: I also need the REAPER project.

**Comment by arthurmcarthur1** [comment] 2022-04-08 16:05
It happens on a blank project too: I can insert ReaLearn on a new track in a clean project, start adding tracks below it and see the same problem.

**Comment by helgoboss** [comment] 2022-04-08 16:16
It's quite possible that things get slower with such a high number of tracks. Selecting many tracks at once fires many events that ReaLearn needs to process. I can look into it at some point. If you want to speed things up, you can also look into it yourself a bit, analyze where ReaLearn spends most time (using a profiler or Realearn's [Prometheus endpoint](https://github.com/helgoboss/realearn/blob/master/CONTRIBUTING.adoc#81-prometheus-endpoint)).

**Comment by arthurmcarthur1** [comment] 2022-04-08 18:03
In the original json with the fx parameters mappings, the problem was approx 10x worse. At 100 tracks, selecting just 5 tracks  resulted in a noticeable lag. 

I wish I knew more coding to look into it, I just started scripting last year and Rust/profiling looks a bit complex at the moment.

**Comment by helgoboss** [comment] 2022-04-10 10:09
I understand. I will have a look at some point. This can probably be improved.

**Comment by arthurmcarthur1** [comment] 2022-06-18 06:16
I'm wondering if you had a chance to look and see if GUI performance in projects with large track counts can be improved. I've been building a new template to use with ReaLearn at the heart of it, aimed at live perfomance and looping via a lua script I'm hacking together. The project is large-ish (nearing 200 tracks and will hopefully end up under 300). 

To try to get around the GUI issue I've tried a new approach with ReaLearn: instead of one massive instance on the monitoring chain with FX parameters mappings via Track: <by name> targets, I've broken it down into one-per-track instances with Track: <This> targets. But the GUI performance hit is still quite high and makes it unusable in this project. And I want many many more instances of ReaLearn and mappings!

**Comment by helgoboss** [comment] 2022-06-18 09:31
Not yet. But looking into it now.

I reproduced some performance issues with your preset and I will try to find a solution for this. But I'm not sure if what I see is the same thing you are seeing. **Please confirm if this is the same issue you are experiencing.**

## Preparation

1. Add 1000 tracks using "Insert multiple tracks".
2. Add one ReaLearn instance to e.g. the first track.
3. Import your preset JSON mentioned in this post: https://github.com/helgoboss/realearn/issues/553#issuecomment-1093001420

## Provoking the slowdown

1. Press "Play"
    - Doing that is an easy way to detect GUI unresponsiveness because we can look at the position display, which is supposed to  run more or less continuously if everything is normal.
    - Whenever one processing step takes too long, we will see a noticeable lag in the position display.
2. Optional: Scroll up and down in a fast way
    - This creates a noticeable lag in the position display but this is not ReaLearn's fault. It also occurs without ReaLearn. Plus, this is not a big issue. So let's move on.
3. Select all tracks at once or unselect all tracks at once
    - **This causes an annoying slowdown.**
    - The position display goes in a stop-and-go mode for about 16 seconds, where each stop period takes app. 1 second.

## Evaluation

- The issue is probably that ReaLearn internally translates creates one event per track selection/unselection. 1000 events in our case.
- Each of these events makes ReaLearn two main things:
    1. Send feedback if necessary
    2. Re-resolve targets (e.g. resolving the first selected track)
- I temporarily disabled step 2 (resolving targets), and really: **This makes the lag disappear.**
- This means there are at least 2 obvious ways to approach this:
   a. Don't create 1000 events but create one batch event instead.
   b. Make target resolving fast.
- (a) sounds like the best way because re-resolving targets 1000 times doesn't make sense anyway. Only 1 time is necessary. Also, it will probably solve a bunch of other potential performance issues related to batch selection/unselection or other user-triggered changes in REAPER where multiple objects (tracks etc.) are affected at once.

## Big question

@arthurmcarthur1 **Do you see serious GUI sluggishness also if you don't change multiple objects at once?**

**Comment by helgoboss** [comment] 2022-06-18 11:45
Good news: I fixed that particular lag! Selecting/unselecting 1000 tracks is not an issue anymore thanks to event batching.

I will release pre.8 later today which contains this fix. Please check.

**Comment by helgoboss** [comment] 2022-06-18 11:58
Closing this to have a better overview. If this is still a thing in pre.8, just open it again.

**Closed by helgoboss** 2022-06-18 11:58 UTC
Labels: bug, question

**Comment by helgoboss** [comment] 2022-06-18 12:48
I was still some slowdowns when the ReaLearn GUI is open. But this is a topic for another ticket because it's much less urgent.

**Comment by arthurmcarthur1** [comment] 2022-06-18 22:37
It's working beautifully for me now! Even across thousands of mappings and track. I do notice a little slowdown as well with the GUI is open, but it's very minor. Thank you, Helgo!

**Comment by helgoboss** [comment] 2022-06-19 05:54
Cool! Happy to hear that.

**Comment by arthurmcarthur1** [comment] 2022-07-31 03:41
I'm running into performance issues again with my current template. I've got about 300 mappings spread across instances on multiple tracks and about 700-800 on the monitoring FX, with a track count of about 230. I'm noticing laggy behavior when selecting tracks, stemming mostly from the monitoring FX instance. It's not debilitating yet but I'd like to increase the mappings by at least 2x, which when I test it out, does make for an unusable lag. I realize I'm pushing the limits here but my questions are: is it possible to improve performance further, or, if not, could I share with you my project and/or ReaLearn preset so you can identify any best practices that would help?
