### ISSUE TITLE
realearn 2 starting with error in ubuntu 18.04, wine 32bit, reaper 32bit

### ISSUE THREAD

**Issue by michaelsjackson** [helgoboss/realearn#144] opened 2021-02-13 01:10 UTC
But did not remove Realearn 1 first, maybe this is the reason, will test that variant as well. Here the error I got, just for reference, maybe it helps:

```
===== ATTENTION =====

Sorry, an unknown error occurred in REAPER plug-in ReaLearn. REAPER should continue to work but ReaLearn might show unexpected behavior until restarting REAPER. If you feel like saving your project file at this point, better save it as a new file because this error could have messed up the plug-in state. 

In any case, please report this error:

1. Prepare an e-mail containing:
    - The error information further below (IMPORTANT)
    - Some instructions on how to reproduce the error (IMPORTANT)
2. If possible, attach the following files: 
    - Your REAPER project file (.rpp)
    - Your REAPER configuration file (reaper.ini)
3. Send it to info@helgoboss.org

Thank you for your support!

--- cut ---
Module name:         ReaLearn
Module version:      v2.0.1/x86 rev efbf25 (2021-02-09 21:45:36 UTC)
Module base address: 0x1c800000
Module size:         0x964000

Message: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

   0: 0x1ce6c792 - Extended
   1: 0x1cd875fc - VSTPluginMain
   2: 0x1ce89667 - Extended
   3:       0x34 - <unknown>
   4: 0xec835657 - <unknown>
--- cut ---


```

**Comment by helgoboss** [comment] 2021-02-13 11:36
Sorry, wrong issue referenced in commit.

**Comment by michaelsjackson** [comment] 2021-02-13 11:52
I also tried deleting realearn 1, its .dll from my vst plugins directory, did not change anything, same error, so it seems to be independent on that. Just as an additional info.

**Comment by helgoboss** [comment] 2021-02-13 11:59
Okay. I'm not really inclined to fix this at the moment since I'm not at all familiar with Wine. Is there any chance you can use REAPER natively on Linux?

**Comment by michaelsjackson** [comment] 2021-02-13 12:00
Did not investigate your system fully yet, but its main power seems coming from the "virtual controls" which is just great!  In future I can try to compare, how I tried to generate similar "virtual controls" via other means, using various other tools for Reaper, scripts, internal or external, just as an inbetween layer.   Would be great to know how you came up with this concept, where you got the idea for it?

**Comment by michaelsjackson** [comment] 2021-02-13 12:02
> Okay. I'm not really inclined to fix this at the moment since I'm not at all familiar with Wine. Is there any chance you can use REAPER natively on Linux?

No problem, not hurrying at all. If this will not work, then not. I can try native linux version as well, as a different story then of course.  Also someone else might look into it, in future, here we kept its report at least.   Anything which is not fun, should not be done.

**Comment by michaelsjackson** [comment] 2021-02-13 12:05
Do you have any guessings which files could cause this in your project, where to look first, any hints?

**Comment by helgoboss** [comment] 2021-02-13 12:23
This seems to be a very low-level error which occurs right at the start when loading the VST plug-in. On the first sight, the backtrace doesn't give any helpful hints where the error could be, that's also why I'm so hesitating looking into it. It also seems the original error is hidden. Some debugging might help.

**Comment by helgoboss** [comment] 2021-02-13 12:36
> Did not investigate your system fully yet, but its main power seems coming from the "virtual controls" which is just great! In future I can try to compare, how I tried to generate similar "virtual controls" via other means, using various other tools for Reaper, scripts, internal or external, just as an inbetween layer. Would be great to know how you came up with this concept, where you got the idea for it?

Yes, I guess the virtual controls can be very helpful. I was planning to implement that concept already long ago for another envisioned plug-in named "SoundPot" (which was too big in scope for me at that time, so I never managed to push it beyond prototype stage). But then I found that ReaLearn could profit from the same concept, too ... and eventually maybe even evolve into something similar like "SoundPot". I think the idea itself is not really new or unique. It's the first logical step if your goal is to decouple 2 things, in this case decoupling controllers from what is being controlled. "Decoupling" is something that many developers are very familiar with :)

**Comment by michaelsjackson** [comment] 2021-02-13 19:58
Except Reaper devs maybe, at least regarding to midi mapping, as you said well in your video.  :-)

In your launch.json, for portable Windows 32-bit, you have this, but my Reaper.exe is somewhere else, can this be the problem? My reaper.exe is in `C:\\Program Files\\REAPER\\reaper.exe`

```
        {
            "name": "Portable Windows 32-bit",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "C:\\REAPER32\\reaper.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false
        },

```

**Comment by helgoboss** [comment] 2021-02-15 10:26
This file is just intended for debugging ony my machine via Visual Studio Code. It doesn't affect anything else.

**Comment by michaelsjackson** [comment] 2021-02-15 12:20
Ok, thanks.

**Comment by helgoboss** [comment] 2021-03-09 23:32
@michaelsjackson I ran into a similar error (`PoisonError`) today on Windows and confirmed that it hides the real error. 2.7.1 shouldn't hide the real error anymore. So if you want to give it another try on Wine ... maybe the error message will be clearer this time.

**Comment by helgoboss** [comment] 2022-04-05 06:57
I'm going to close this for now. I feel that with yabridge, there's no reason anymore to prefer running REAPER on Wine over running it on Linux natively.

**Closed by helgoboss** 2022-04-05 06:57 UTC
Labels: enhancement, low priority, hard
