### ISSUE TITLE
Add support for non-normalized OSC values (greater than 1.0)

### ISSUE THREAD

**Issue by MusicIsMedicine** [helgoboss/realearn#490] opened 2021-12-05 20:50 UTC
Helgoboss,

I've ran into an issue with OSC as a target.
The plugin I'm trying to control accepts OSC natively.., I put in the address and eveything works.
However some of the paramaters are setup to accept the actual float value, not the normalized 0.0-1.0 range.
So just as an example; if the paramater's range is 0.0-20.0, I'm not able to reach values above 1.0.
There are some parameters that go as high as 20000, so a
nice high range would be good, maybe at least 100000, or if you wanted to allow for the full float range, that would be great too.

Sooo, do you think you could increase ReaLearn's range for OSC float output?
Also it would be nice to have a few more decimal places of percession for fields that support it like, (Value Sequence, Target: Min/Max, and Step Size: Min/Max).

Thank you,
James

**Comment by helgoboss** [comment] 2021-12-05 22:03
I can make available a new field in the OSC source for defining the maximum value. And then 0.0 will be interpreted as 0% of the value range and this defined max value as 100%.

As for the other fields like target min/max, changing the value range would be pointless and make no difference at all other than cause confusion. ReaLearn has the concept of value ranges: There's a minimum and a maximum. In the user interface the minimum is displayed as 0% and the maximum as 100% (because users of all backgrounds probably understand what percentages are). In more mathematical contexts such as transformation formulas or dynamic expressions, the minimum is expressed as 0.0 and the maximum as 1.0. It's the same! That's just ReaLearn source/target-neutral normalization.

There's also absolutely no difference in precision, as you might think. These are floating point numbers, so the precision you can achieve between 0.0 and 1.0 is the same as the one that you can achieve with a number between 0.0 and 10000000.0

**Comment by MusicIsMedicine** [comment] 2021-12-05 23:22
That sounds good :). As for the second part about Step Size: Min/Max and such, I was looking to get finer granularity to the right side of the decimal, I think the lowest I could go was 0.001. It's for a reascript I
was working on in which I am sending OSC to the script which uses get_action_context() to translate the value and pass it onto SNM_SetDoubleConfigVar() which is controlling REAPER's playrate. 
You're probably saying to yourself "why not just use the built in playrate source destination of ReaLearn?"  ;) 
...well doing it via SNM_SetDoubleConfigVar() I am able to attain values way outside the normal bounds that REAPER "normally" allows.

**Comment by helgoboss** [comment] 2021-12-06 16:46
Ah, I get it. Actually, ReaLearn lets you enter numbers with many decimal digits and processes them. It just doesn't display them. This is really counter-intuitive, so I opened #491 to fix that.

As for the out-of-normal-range playrate stuff, this is something I don't know yet how to tackle elegantly. This is potentially also relevant for other parameters such as track volume, which could go out of range, too (although this is probably not too useful).

**Comment by meta-meta** [comment] 2021-12-23 00:50
Sorry to hijack the thread, but I was wondering if it is possible to invoke a Reascript from OSC and get values other than a normalized float via `get_action_context()`. It's not clear to me whether that's a limitation of the Reasript API or Reaper's OSC implementation. I haven't dug into the code but it seems Realearn has its own OSC server and maybe you have more control this way?

**Comment by helgoboss** [comment] 2021-12-24 11:12
You mean you would like to parameterize the ReaScript call e.g. with a string, not just a float? I would love that as well, but I don't think it's possible with the ReaScript API at the moment. So it's primarily a limitation of the ReaScript API. If this limitation is lifted by the REAPER devs, I would love to extend the "Invoke action" target with a way to forward certain parts of the OSC message to the ReaScript.

**Comment by meta-meta** [comment] 2021-12-24 17:03
Exactly. OK thank you, good to know where the limitation is. I'm brand new to ReaScript and that was an immediate disappointment. ReaLearn however is a delight and I believe it will take me very far. 🙏

**Comment by meta-meta** [comment] 2021-12-24 17:52
Posted in Feature Requests 🤞
https://forum.cockos.com/showthread.php?p=2509834#post2509834

**Comment by helgoboss** [comment] 2022-04-04 22:15
This is actually a duplicate of #403, which I'm implementing right now.

**Closed by helgoboss** 2022-04-04 22:15 UTC
Labels: enhancement, high priority
