### ISSUE TITLE
Feature Request:  Track targets adhere to Reaper grouping / ganging behavior

### ISSUE THREAD

**Issue by RattlesnakeLodge** [helgoboss/realearn#690] opened 2022-09-24 01:37 UTC

**Comment by RattlesnakeLodge** [comment] 2022-09-24 02:33
Greetings!

Is it possible to configure Track targets to respect Reaper Track grouping / ganging, same as the behavior in Reaper's own GUI mixer, driven with a mouse?

For example, in a Reaper Track Group, moving the fader for a track tagged with "Volume Lead" will also move the fader, relatively, for another track in the group tagged "Volume Follow".

Another example is if multiple tracks are selected.  Moving controls for one of the selected tracks will cause a relative change to the other selected tracks.

Video Example:  https://photos.app.goo.gl/aETyZhJvRSAhWxoPA


The track targets should include...

Volume
Pan
Pan Width
Solo
Rec Arm
Mute
Input Monitor Mode
Polarity / Phase invert
Automation Touch State
**  If plans to include new track targets in the future, Track Input is also ganged in Reaper **

**Comment by helgoboss** [comment] 2022-09-24 07:22
This is a duplicate of #45. Please comment/vote there.

**Closed** 2022-09-24 07:23 UTC
