### ISSUE TITLE
FR : Raw MIDI source for control direction

### ISSUE THREAD

**Issue by cjunekim** [helgoboss/realearn#384] opened 2021-06-11 15:24 UTC
As written in the manual,

> It only supports feedback direction at the moment because I couldn't ﬁnd a use case yet for control direction. If you also need it for control direction, please put a feature request, it's not diﬃcult to add.

I am putting a feature request for this. The use case is, my most midi controllers have its own custom buttons. I want to make use of it for controlling other things. For example, nanoKONTROL Studio has Scene button and it will let you switch midi settings scenes(or banks). I'd like to make use of this button for controlling.

**Comment by helgoboss** [comment] 2021-06-12 16:52
This is a duplicate of #376. Feel free to vote there.

**Closed by helgoboss** 2021-06-12 16:52 UTC
Labels: duplicate

**Comment by helgoboss** [comment] 2021-06-12 16:53
BTW, what kind of MIDI message does your nanoKONTROL custom button send? Sys-ex? Because if it's not sys-ex, you probably wouldn't need this.

**Comment by cjunekim** [comment] 2021-06-12 18:43
> BTW, what kind of MIDI message does your nanoKONTROL custom button send? Sys-ex? Because if it's not sys-ex, you probably wouldn't need this.

It's sysex. For example, each time I press Scene button, the MIDI-OX shows:

```
00000C32   2  --     F0  Buffer:    12 Bytes   System Exclusive  
SYSX: F0 42 40 00 01 37 02 00 00 4F 01 F7
0000232C   2  --     F0  Buffer:    12 Bytes   System Exclusive  
SYSX: F0 42 40 00 01 37 02 00 00 4F 02 F7

```
You see 4F 01 F7 and then 4F 02 F7. The increasing value refers to the current Scene ID.
